pipeline
    agent any
    environment {
        VERSION="1.0"
    }
    stages{
        stage('Cloning repo'){
                git 'https://github.com/Joginator4/Jenkins'
        }
    }
    stage('Check if Jenkinsfile Works'){
        steps{
            echo ${VERSION}
        }
    }