---
- name: deploy nginx
  hosts: cluster
  become: true
  become_user: ubuntu

  tasks:
    - name: Preparing Kubernetes environment to work
      shell:
        cmd: echo "alias k=kubectl" >> /home/ubuntu/.bashrc; source bashrc

    - name: Copy kubernetes yaml files to Kubernetes server
      shell:
        cmd: scp -r ubuntu@172.31.15.124:/home/ubuntu/Kubernetes_yaml/*.yml /home/ubuntu/Deployment 
    - name: Create nginx deployment
      shell:
        cmd: kubectl apply -f /home/ubuntu/Deployment.yml
    - name: Create service
      shell:
        cmd: kubectl apply -f Service.yml