---
- name: deploy nginx
  hosts: cluster
  become: true
  become_user: ubuntu

  tasks:
    - name: Create nginx deployment
      shell:
        cmd: kubectl apply -f /home/ubuntu/ansible-inventory/Deployment.yaml
    - name: Create service
      shell:
        cmd: kubectl apply -f /home/ubuntu/ansible-inventory/Service.yaml