apiVersion: v1
kind: Service
metadata:
  name: srv-nginx
spec:
  type: NodePort
  selector:
    matchLabels:
      app: nginx
    ports:
      - protocol: TCP
        port: 80
        targetPort: 9000

        nodePort: 30007